AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/hello-world/
      Handler: index.handler
      Runtime: nodejs16.x
      Events:
        HelloApi:
          Type: Api
          Properties:
            Path: /hello
            Method: get